###
post http://localhost:4000/user
Content-Type: application/json


{
    "userid":"678fJx",
    "name":"MARY",
    "password":"pxWhA43542",
    "email":"marymumbi1212@gmail.com",
    "role":"users"
}

###

get http://localhost:4000/user/one?email=john@gmaiddfa.com
 

###
get http://localhost:4000/user/all

###
get http://localhost:4000/user?userid=5768w


###
post http://localhost:4000/user/login
Content-Type: application/json


{
    "password":"pxWhA43542",
    "email":"marymumbi1212@gmail.com"


}

###
DELETE http://localhost:4000/null
