###
post http://localhost:4000/user
Content-Type: application/json

{
    "userid":"7623HDJ5YY623S",
    "name":"chrdsis5ewb35",
    "password":"erqA432",
    "email":"chrilvcdydbYUERqyfseY@gmail.com",
    "role":"users"
}

###

get http://localhost:4000/user/one?email='chrilvcdydbYUERqyfseY@gmail.com'


###
get http://localhost:4000/user/all



###
post http://localhost:4000/user?login
Content-Type: application/json

{
    "userid":"7623HDJ5YY623S",
    "name":"chrdsis5ewb35",
    "password":"erqA432",
    "email":"chrilYUERY@gmail.com",
     "role":"users"
}